/**
 * ship.fairtech.kr - 항만 가이드 데이터
 * 모든 기관 데이터 (지방청, 항만공사, 도선사회, 산하기관, 세관, 해경, 검역)
 *
 * 이 파일은 port-atlas-header.js보다 먼저 로드되어야 함 (loader.js에서 보장)
 *
 * window.PORT_ATLAS_DATA를 통해 전역 접근.
 */

(function () {
  'use strict';

  // ============================================================
  // 1. 해양수산부 (총괄)
  // ============================================================
  const MOF = {
    name: '해양수산부',
    nameEn: 'Ministry of Oceans and Fisheries',
    abbr: 'MOF',
    headquarters: '부산광역시 동구 중앙대로 361번길 14 (아이엠빌딩)',
    note: '2025년 세종 → 부산 이전. 정부세종청사에 일부 부서 잔존.',
    url: 'https://www.mof.go.kr',
    callCenter: '110 (정부민원안내콜센터)',
  };

  // ============================================================
  // 2. 지방해양수산청 (12) — 권역별
  // ============================================================
  const OFFICES = {
    수도권충청: {
      color: '#14b8a6',
      label: '수도권·충청',
      items: [
        { name: '인천지방해양수산청', port: '인천항', url: 'https://incheon.mof.go.kr', portKey: '인천항', address: '인천광역시 중구 서해대로 365-1', postcode: '22346', tel: '032-880-6114', fax: '032-882-4642' },
        { name: '평택지방해양수산청', port: '평택·당진항', url: 'https://pyeongtaek.mof.go.kr', portKey: '평택·당진항', address: '경기도 평택시 포승읍 평택항만길 116 (만호리 566)', postcode: '17962', tel: '031-683-0313', fax: '031-680-7219' },
        { name: '대산지방해양수산청', port: '대산항', url: 'https://daesan.mof.go.kr', portKey: '대산항', address: '충청남도 서산시 홍천로 42 (잠홍동)', postcode: '32002', tel: '041-660-7700', fax: '041-663-0356' },
      ],
    },
    호남: {
      color: '#fbbf24',
      label: '호남',
      items: [
        { name: '군산지방해양수산청', port: '군산항', url: 'https://gunsan.mof.go.kr', portKey: '군산항', address: '전북 군산시 설림길 11 (소룡동)', postcode: '54014', tel: '063-441-2223', telNight: '063-441-2208', telCivil: '063-441-2204', fax: '063-441-2352' },
        { name: '목포지방해양수산청', port: '목포항', url: 'https://mokpo.mof.go.kr', portKey: '목포항', address: '전라남도 목포시 통일대로 130 (옥암동)', postcode: '58746', tel: '061-280-1700', fax: '061-280-1703' },
        { name: '여수지방해양수산청', port: '광양·여수항', url: 'https://yeosu.mof.go.kr', portKey: '광양항', address: '전라남도 여수시 여서1로 107', postcode: '59713', tel: '061-650-6000', fax: '061-654-2353' },
      ],
    },
    영남: {
      color: '#f97316',
      label: '영남',
      items: [
        { name: '부산지방해양수산청', port: '부산항', url: 'https://busan.mof.go.kr', portKey: '부산항', address: '부산광역시 동구 충장대로 351 (좌천동)', postcode: '48755', tel: '051-609-6114', fax: '051-609-6219' },
        { name: '마산지방해양수산청', port: '마산항', url: 'https://masan.mof.go.kr', portKey: '마산항', address: '경상남도 창원시 마산합포구 제2부두로 10 (정부경남지방합동청사)', postcode: '51716', tel: '055-981-5000', fax: '055-245-0885' },
        { name: '울산지방해양수산청', port: '울산항', url: 'https://ulsan.mof.go.kr', portKey: '울산항', address: '울산광역시 남구 장생포고래로 288번길 6', postcode: '44780', tel: '052-228-5500', fax: '052-228-5549' },
        { name: '포항지방해양수산청', port: '포항항', url: 'https://pohang.mof.go.kr', portKey: '포항항', address: '경상북도 포항시 북구 해동로 376', postcode: '37716', tel: '054-242-1812', fax: '054-245-1649' },
      ],
    },
    동해안: {
      color: '#ef4444',
      label: '동해안',
      items: [
        { name: '동해지방해양수산청', port: '동해·묵호항', url: 'https://donghae.mof.go.kr', portKey: '동해·묵호항', address: '강원도 동해시 평원로 46', postcode: '25752', tel: '033-520-6000', telNight: '033-520-6200' },
      ],
    },
    제주: {
      color: '#a78bfa',
      label: '제주',
      items: [
        { name: '제주해양수산관리단', port: '제주항', url: 'https://busan.mof.go.kr', portKey: '제주항', sub: '부산청 산하', note: '지리적으로 제주에 위치하나, 해양수산부 조직 직제상 부산지방해양수산청 산하 관리단으로 편제됨' },
      ],
    },
  };

  // ============================================================
  // 3. 항만공사 (5)
  // ============================================================
  const PORT_AUTHORITIES = [
    { name: '부산항만공사', abbr: 'BPA', port: '부산항', url: 'https://www.busanpa.com', portKey: '부산항', address: '부산광역시 중구 대교로 122 (중앙동6가)', postcode: '48943', tel: '051-999-3000', fax: '051-999-3295' },
    { name: '인천항만공사', abbr: 'IPA', port: '인천항', url: 'https://www.icpa.or.kr', portKey: '인천항', address: '인천광역시 연수구 센트럴로 263, IBS 타워 (31~35F)', postcode: '22006', tel: '032-890-8000', fax: '032-726-0311' },
    { name: '여수광양항만공사', abbr: 'YGPA', port: '광양·여수항', url: 'https://www.ygpa.or.kr', portKey: '광양항', address: '전라남도 광양시 항만대로 465', postcode: '57771', tel: '061-797-4300', fax: '061-797-4502' },
    { name: '울산항만공사', abbr: 'UPA', port: '울산항', url: 'https://www.upa.or.kr', portKey: '울산항', address: '울산광역시 남구 장생포고래로 271', postcode: '44780', tel: '052-228-5300', fax: '052-228-5369' },
    { name: '경기평택항만공사', abbr: 'GPPC', port: '평택·당진항', url: 'https://www.gppc.or.kr', portKey: '평택·당진항', sub: '지방공기업', address: '경기도 평택시 포승읍 평택항만길 73, 10층 (평택항마린센터)', tel: '031-686-0600', fax: '031-686-0641' },
  ];

  // ============================================================
  // 4. 도선사회 (13)
  // ============================================================
  const PILOTS = [
    {
      name: '한국도선사협회',
      abbr: 'KMPA',
      url: 'https://www.kmpilot.or.kr',
      sub: '총괄 협회',
      address: '서울특별시 영등포구 국회대로76길 18, 10층 (여의도동, 오성빌딩)',
      postcode: '07238',
      tel: '02-784-6022',
      fax: '02-783-0931',
      email: 'kmpilot@kmpilot.or.kr',
    },
    {
      name: '부산항도선사회',
      port: '부산항',
      url: 'http://www.busanpilot.co.kr',
      portKey: '부산항',
      address: '부산광역시 중구 충장대로 24, 201호 (구 국제여객터미널)',
      postcode: '48940',
      tel: '051-465-1651',
      fax: '051-463-1652',
      email: 'bspilot@kmpilot.or.kr',
    },
    {
      name: '인천항도선사회',
      port: '인천항',
      url: 'http://www.incheonpilot.com',
      portKey: '인천항',
    },
    {
      name: '여수항도선사회',
      port: '광양·여수항',
      url: 'http://www.yspilot.co.kr',
      portKey: '광양항',
      address: '전라남도 여수시 공화북6길 37 (덕충동)',
      postcode: '59724',
      tel: '061-660-1300',
      fax: '061-666-0322',
      email: 'yspilot3@hanmail.net',
    },
    {
      name: '울산항도선사회',
      port: '울산항',
      url: 'https://www.kmpilot.or.kr',
      portKey: '울산항',
      note: '협회 본부 사이트 참조',
    },
    {
      name: '평택당진항도선사회',
      port: '평택·당진항',
      url: 'https://www.kmpilot.or.kr',
      portKey: '평택·당진항',
      note: '협회 본부 사이트 참조',
    },
    {
      name: '대산항도선사회',
      port: '대산항',
      url: 'https://www.kmpilot.or.kr',
      portKey: '대산항',
      note: '협회 본부 사이트 참조',
    },
    {
      name: '마산항도선사회',
      port: '마산항',
      url: 'https://www.kmpilot.or.kr',
      portKey: '마산항',
      note: '협회 본부 사이트 참조',
    },
    {
      name: '포항항도선사회',
      port: '포항항',
      url: 'https://www.kmpilot.or.kr',
      portKey: '포항항',
      note: '협회 본부 사이트 참조',
    },
    {
      name: '군산항도선사회',
      port: '군산항',
      url: 'https://www.kmpilot.or.kr',
      portKey: '군산항',
      note: '협회 본부 사이트 참조',
    },
    {
      name: '목포항도선사회',
      port: '목포항',
      url: 'http://www.mppilot.co.kr',
      portKey: '목포항',
      note: '자체 사이트 운영 (조직도 미공개)',
    },
    {
      name: '동해항도선사회',
      port: '동해·묵호항',
      url: 'https://www.kmpilot.or.kr',
      portKey: '동해·묵호항',
      note: '협회 본부 사이트 참조',
    },
    {
      name: '제주항도선사회',
      port: '제주항',
      url: 'https://www.kmpilot.or.kr',
      portKey: '제주항',
      note: '협회 본부 사이트 참조',
    },
  ];

  // ============================================================
  // 5. 해수부 산하기관
  // ============================================================
  const MOF_AGENCIES = [
    { name: '한국해양교통안전공단', abbr: 'KOMSA', url: 'https://www.komsa.or.kr', role: '선박검사·해상교통안전' },
    { name: '한국해양수산개발원', abbr: 'KMI', url: 'https://www.kmi.re.kr', role: '해양수산 정책 연구' },
    { name: '한국해양과학기술원', abbr: 'KIOST', url: 'https://www.kiost.ac.kr', role: '해양과학기술 연구' },
    { name: '국립해양조사원', abbr: 'KHOA', url: 'https://www.khoa.go.kr', role: '수로·해양조사' },
    { name: '국립수산과학원', abbr: 'NIFS', url: 'https://www.nifs.go.kr', role: '수산 연구' },
    { name: '해양환경공단', abbr: 'KOEM', url: 'https://www.koem.or.kr', role: '해양환경 보전·방제' },
    { name: '한국해양수산연수원', abbr: 'KIMFT', url: 'https://www.seaman.or.kr', role: '선원 교육·훈련' },
    { name: '국립해양박물관', abbr: 'NMM', url: 'https://www.nmm.go.kr', role: '해양문화 유산 (부산)' },
    { name: '국립해양생물자원관', abbr: 'MABIK', role: '해양생물자원 (서천)' },
    { name: '한국수산자원공단', abbr: 'FIRA', role: '인공어초·바다숲·종묘방류' },
  ];

  // ============================================================
  // 6. 관세청
  // ============================================================
  const CUSTOMS_HQ = [
    {
      name: '광주본부세관',
      fullName: '광주본부세관',
      role: '호남권 본부',
      url: 'https://www.customs.go.kr/gwangju/main.do',
      address: '광주광역시 북구 첨단과기로208번길 43',
      tel: '062-975-8114',
      sub: '호남권 군산·목포·광양·여수 세관 관할',
    },
    {
      name: '서울본부세관',
      fullName: '서울본부세관',
      role: '수도권 동부 본부',
      url: 'https://www.customs.go.kr/seoul/main.do',
      address: '서울특별시 강남구 언주로 721',
      postcode: '06050',
      tel: '02-510-1114',
      sub: '서울·경기 동부·강원 세관 관할',
    },
  ];

  const CUSTOMS_PORTS = {
    수도권충청: {
      color: '#14b8a6',
      label: '수도권·충청',
      items: [
        {
          name: '인천세관',
          fullName: '인천본부세관',
          role: '인천본부',
          url: 'https://www.customs.go.kr/incheon/main.do',
          portKey: '인천항',
          address: '인천광역시 중구 서해대로 339',
          postcode: '22346',
          tel: '032-452-3114',
          telNight: '032-452-3535',
          note: '2023.4.18 인천공항세관 분리 (TEL 032-722-4114)',
          children: [
            { name: '김포공항세관' },
            { name: '인천공항국제우편세관' },
            { name: '수원세관' },
            { name: '안산세관 (부평지원센터)' },
          ],
        },
        {
          name: '평택세관',
          role: '직할',
          url: 'https://www.customs.go.kr/pyeongtaek/main.do',
          portKey: '평택·당진항',
          address: '경기도 평택시 포승읍 평택항만길 45',
          postcode: '17962',
          tel: '031-8054-7000',
          children: [
            { name: '대산지원센터', tel: '041-419-2714' },
          ],
        },
      ],
    },
    호남: {
      color: '#fbbf24',
      label: '호남',
      items: [
        {
          name: '군산세관',
          role: '광주본부 산하',
          url: 'https://www.customs.go.kr/gunsan/main.do',
          portKey: '군산항',
          address: '전북특별자치도 군산시 해망로 244-7',
          postcode: '54021',
          tel: '063-730-8700',
          fax: '063-730-8729',
        },
        {
          name: '목포세관',
          role: '광주본부 산하',
          url: 'https://www.customs.go.kr/mokpo/main.do',
          portKey: '목포항',
          address: '전남 영암군 삼호읍 유수로 46',
          postcode: '58451',
          tel: '061-460-8515',
          fax: '061-464-1530',
          note: '대불산단 인근. 완도지원센터 운영',
        },
        {
          name: '광양세관',
          role: '광주본부 산하',
          url: 'https://www.customs.go.kr/gwangyang/main.do',
          portKey: '광양항',
          address: '전남 광양시 컨부두로 433 (도이동 806)',
          tel: '061-797-8462',
          telCenter: '061-797-8451',
          fax: '061-795-0361',
          note: '항만주감시소 / 컨테이너검색센터 운영',
        },
        {
          name: '여수세관',
          role: '광주본부 산하',
          url: 'https://www.customs.go.kr/yeosu/main.do',
          portKey: '광양항',
          address: '전남 여수시 웅천북로 39 (웅천동)',
          postcode: '59691',
          tel: '061-660-8600',
          telCivil: '061-660-8631',
          fax: '061-692-8701',
        },
      ],
    },
    영남: {
      color: '#f97316',
      label: '영남',
      items: [
        {
          name: '부산세관',
          fullName: '부산·경남본부세관',
          role: '부산본부',
          url: 'https://www.customs.go.kr/busan/main.do',
          portKey: '부산항',
          address: '부산광역시 중구 중앙대로 26 (중앙동 6가 12) — 청사 리모델링 임시 이전',
          postcode: '48942',
          tel: '051-620-6114',
          telCivil: '051-620-6054',
          fax: '051-620-1115',
          children: [
            { name: '김해공항세관' },
            { name: '북부산세관' },
            { name: '양산세관' },
            { name: '창원세관' },
            { name: '마산세관' },
            { name: '경남남부세관' },
            { name: '경남서부세관' },
          ],
        },
        {
          name: '마산세관',
          role: '부산본부 산하',
          url: 'https://www.customs.go.kr/masan/main.do',
          portKey: '마산항',
          address: '경상남도 창원시 마산합포구 제2부두로 10, 정부경남지방합동청사 7~8층',
          postcode: '51716',
          tel: '055-248-1822',
          fax: '055-981-7019',
        },
        {
          name: '울산세관',
          role: '부산본부 산하',
          url: 'https://www.customs.go.kr/ulsan/main.do',
          portKey: '울산항',
          postcode: '44780',
          branchTitle: '울산세관 통선장',
          branchAddress: '울산광역시 남구 장생포고래로 178 (장생포동)',
        },
        {
          name: '포항세관',
          role: '대구본부 산하',
          url: 'https://www.customs.go.kr/pohang/main.do',
          portKey: '포항항',
          address: '포항시 북구 해안로 7 (항구동)',
          postcode: '37708',
          tel: '054-720-5714',
          telCenter: '054-720-5733',
          telPort: '054-720-5751',
          fax: '054-244-5794',
          note: '수출입민원 / 환급보민원 / 항만감시민원 회선 분리 · 경북 권역 세관은 행정상 대구본부세관 관할 (부산본부가 아님)',
        },
      ],
    },
    동해안: {
      color: '#ef4444',
      label: '동해안',
      items: [
        {
          name: '동해세관',
          role: '서울본부 산하',
          url: 'https://www.customs.go.kr/donghae/main.do',
          portKey: '동해·묵호항',
          address: '강원특별자치도 동해시 천곡로 119 (천곡동 817-1)',
          postcode: '25754',
          tel: '033-539-2662',
          fax: '033-533-7186',
          note: '원주지원센터 운영 · 강원·동해안 권역은 행정상 서울본부세관 관할',
        },
      ],
    },
    제주: {
      color: '#a78bfa',
      label: '제주',
      items: [
        {
          name: '제주세관',
          role: '광주본부 산하',
          url: 'https://www.customs.go.kr/jeju/main.do',
          portKey: '제주항',
          address: '제주도 제주시 공항로 2',
          postcode: '63115',
          tel: '064-797-8800',
          fax: '064-797-8805',
          note: '공항 + 항만 통관 통합 관리 · 제주 권역은 행정상 광주본부세관 관할 (부산본부가 아님)',
        },
      ],
    },
  };

  // ============================================================
  // 7. 해상치안
  // ============================================================
  const KCG_AGENCIES = [
    {
      name: '해양경찰청',
      abbr: 'KCG',
      kind: '본청·지방청',
      url: 'https://www.kcg.go.kr',
      role: '본청 — 해상경비·구조·방제·항만보안 (해양수산부 외청)',
      address: '인천광역시 연수구 해돋이로 130',
      lat: 37.3937146,
      lng: 126.6494369,
    },
    {
      name: '중부지방해양경찰청',
      abbr: 'KCG 중부청',
      kind: '본청·지방청',
      url: 'https://www.kcg.go.kr/jbcgh/main.do',
      portKey: '인천항',
      role: '인천·경기·충남 해역 — 인천항 일대',
      address: '인천광역시 연수구 신항대로 263',
      note: '2025년 시흥 배곧 이전 예정',
      lat: 37.3625,
      lng: 126.6147,
    },
    {
      name: '남해지방해양경찰청',
      abbr: 'KCG 남해청',
      kind: '본청·지방청',
      url: 'https://www.kcg.go.kr/namhaecgh/main.do',
      portKey: '부산항',
      role: '부산·울산·경남 해역 — 부산항·울산항·마산항·진해항·통영',
      postcode: '48755',
      address: '부산광역시 동구 충장대로 325',
      tel: '051-663-2000',
      lat: 35.119217,
      lng: 129.04667,
    },
    {
      name: '서해지방해양경찰청',
      abbr: 'KCG 서해청',
      kind: '본청·지방청',
      url: 'https://www.kcg.go.kr/shcgh/main.do',
      portKey: '목포항',
      role: '전북·전남 서해 — 군산항·목포항·완도',
      address: '전라남도 목포시 옥암로 24',
      lat: 34.8052051,
      lng: 126.4281632,
    },
    {
      name: '동해지방해양경찰청',
      abbr: 'KCG 동해청',
      kind: '본청·지방청',
      url: 'https://www.kcg.go.kr/dhcgh/main.do',
      portKey: '동해·묵호항',
      role: '강원·경북 해역 — 동해항·묵호항·포항·울산 일부',
      address: '강원특별자치도 동해시 이원길 156',
      lat: 37.4798271,
      lng: 129.1019959,
    },
    {
      name: '제주지방해양경찰청',
      abbr: 'KCG 제주청',
      kind: '본청·지방청',
      url: 'https://www.kcg.go.kr/jejucgh/main.do',
      portKey: '제주항',
      role: '제주 해역 전체',
      address: '제주특별자치도 제주시 구산로 65',
      postcode: '63236',
      tel: '064-801-2000',
      telPlanning: '064-801-2516',
      note: '제주해양경찰서 + 서귀포해양경찰서 + 제주광역해상교통관제센터 산하',
      lat: 33.4835392,
      lng: 126.5392137,
    },
    // ===== 해양경찰서 (12) — 무역항 매칭 =====
    {
      name: '인천해양경찰서',
      abbr: 'KCG 인천',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/inchoncgs/main.do',
      portKey: '인천항',
      role: '인천항 해역 치안·수색구조·정보',
      parent: '중부지방해양경찰청',
      postcode: '22761',
      address: '인천광역시 서구 청라루비로 96',
      tel: '032-650-2000',
      telOffice: '032-650-2516',
      lat: 37.5264759,
      lng: 126.6411219,
    },
    {
      name: '평택해양경찰서',
      abbr: 'KCG 평택',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/pyeongtaekcgs/main.do',
      portKey: '평택·당진항',
      role: '평택·당진 해역 치안·수색구조·정보',
      parent: '중부지방해양경찰청',
      postcode: '17967',
      address: '경기도 평택시 포승읍 서동대로 437-27',
      tel: '031-8046-2000',
      telOffice: '031-8046-2516',
      lat: 36.9830892,
      lng: 126.885256,
    },
    {
      name: '태안해양경찰서',
      abbr: 'KCG 태안',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/taeancgs/main.do',
      portKey: '대산항',
      role: '대산항·태안 해역 치안·수색구조·정보',
      parent: '중부지방해양경찰청',
      postcode: '32145',
      address: '충청남도 태안군 태안읍 동백로 92-13',
      tel: '041-950-2000',
      telOffice: '041-950-2216',
      lat: 36.7490797,
      lng: 126.3027089,
    },
    {
      name: '군산해양경찰서',
      abbr: 'KCG 군산',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/gunsancgs/main.do',
      portKey: '군산항',
      role: '군산항 해역 치안·수색구조·정보',
      parent: '서해지방해양경찰청',
      postcode: '54018',
      address: '전북특별자치도 군산시 군산창길 21',
      tel: '063-539-2000',
      telOffice: '063-539-2416',
      lat: 35.9933844,
      lng: 126.7086213,
    },
    {
      name: '목포해양경찰서',
      abbr: 'KCG 목포',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/mokpocgs/main.do',
      portKey: '목포항',
      role: '목포항 해역 치안·수색구조·정보',
      parent: '서해지방해양경찰청',
      postcode: '58623',
      address: '전라남도 목포시 청호로 231',
      tel: '061-241-2000',
      lat: 34.8096953,
      lng: 126.3679345,
    },
    {
      name: '여수해양경찰서',
      abbr: 'KCG 여수',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/yeosucgs/main.do',
      portKey: '광양항',
      role: '광양·여수항 해역 치안·수색구조·정보',
      parent: '서해지방해양경찰청',
      postcode: '59700',
      address: '전라남도 여수시 문수로 111',
      tel: '061-840-2000',
      telOffice: '061-840-2516',
      lat: 34.7574899,
      lng: 127.7095769,
    },
    {
      name: '부산해양경찰서',
      abbr: 'KCG 부산',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/busancgs/main.do',
      portKey: '부산항',
      role: '부산항 본항·신항·감천 해역 치안·수색구조·정보',
      parent: '남해지방해양경찰청',
      postcode: '49111',
      address: '부산광역시 영도구 해양로 293',
      tel: '051-664-2000',
      telOffice: '051-664-2516',
      lat: 35.0993999,
      lng: 129.0580363,
    },
    {
      name: '울산해양경찰서',
      abbr: 'KCG 울산',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/ulsancgs/main.do',
      portKey: '울산항',
      role: '울산항 해역 치안·수색구조·정보',
      parent: '남해지방해양경찰청',
      postcode: '44772',
      address: '울산광역시 남구 신선로 20',
      tel: '052-230-2000',
      telOffice: '052-230-2516',
      lat: 35.5204571,
      lng: 129.3136282,
    },
    {
      name: '창원해양경찰서',
      abbr: 'KCG 창원',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/changwoncgs/main.do',
      portKey: '마산항',
      role: '마산·진해·옥포 해역 치안·수색구조·정보',
      parent: '남해지방해양경찰청',
      postcode: '51716',
      address: '경상남도 창원시 마산합포구 제2부두로 40',
      tel: '055-981-2000',
      telOffice: '055-981-2516',
      lat: 35.1954449,
      lng: 128.5708965,
    },
    {
      name: '포항해양경찰서',
      abbr: 'KCG 포항',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/pohangcgs/main.do',
      portKey: '포항항',
      role: '포항항 해역 치안·수색구조·정보',
      parent: '동해지방해양경찰청',
      postcode: '37642',
      address: '경상북도 포항시 북구 소티재로 151번길 21',
      tel: '054-750-2000',
      telOffice: '054-750-2516',
      lat: 36.0688,
      lng: 129.3733,
    },
    {
      name: '동해해양경찰서',
      abbr: 'KCG 동해',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/donghaecgs/main.do',
      portKey: '동해·묵호항',
      role: '동해·묵호항 해역 치안·수색구조·정보',
      parent: '동해지방해양경찰청',
      postcode: '25730',
      address: '강원특별자치도 동해시 임항로 29',
      tel: '033-741-2000',
      telOffice: '033-741-2216',
      lat: 37.5386737,
      lng: 129.1077386,
    },
    {
      name: '제주해양경찰서',
      abbr: 'KCG 제주',
      kind: '해양경찰서',
      url: 'https://www.kcg.go.kr/jejucgs/main.do',
      portKey: '제주항',
      role: '제주항 해역 치안·수색구조·정보',
      parent: '제주지방해양경찰청',
      postcode: '63280',
      address: '제주특별자치도 제주시 임항로 154',
      tel: '064-766-2000',
      telOffice: '064-766-2216',
      lat: 33.5198831,
      lng: 126.5423918,
    },
  ];

  // ============================================================
  // 8. 검역·검사
  // ============================================================
  const QUARANTINE_AGENCIES = [
    {
      name: '농림축산검역본부',
      abbr: 'QIA',
      url: 'https://www.qia.go.kr',
      role: '동·식물 검역, 외국선박 평형수·선원 검역 (농식품부)',
      address: '경북 김천시 혁신8로 177 (율곡동)',
      postcode: '39660',
      tel: '054-912-1000',
      telNight: '054-912-1001',
    },
    {
      name: '농림축산검역본부 영남지역본부',
      abbr: 'QIA 영남',
      url: 'https://www.qia.go.kr/yeongnam/',
      portKey: '부산항',
      role: '부산항 외국선박 검역, 부산신항·국제여객터미널 사무소 운영',
      address: '부산광역시 중구 중앙대로 30번길 8',
      postcode: '48943',
      telAnimal: '051-600-0400',
      telPlant: '051-600-5804',
      note: '부산항 사무소: 국제여객터미널 3층 / 충장대로 6 한진R&D센터 2층 / 김해공항 국제선 1층',
    },
    {
      name: '농림축산검역본부 호남지역본부',
      abbr: 'QIA 호남',
      url: 'https://www.qia.go.kr/honam/',
      portKey: '광양항',
      role: '광양·여수 외국선박 검역, 광양·광주·전주·무안공항 사무소 운영',
      note: '호남권 무역항 검역 총괄 (본청은 경북 김천 소재)',
    },
    {
      name: '국립수산물품질관리원',
      abbr: 'NFQS',
      url: 'https://www.nfqs.go.kr',
      role: '수산물 검역·품질관리 (해수부)',
    },
    {
      name: '한국선급',
      abbr: 'KR',
      url: 'https://www.krs.co.kr',
      role: '선급 검사·인증 (민간)',
    },
  ];

  // ============================================================
  // 9. 항만보안공사 (ISPS, 부두 출입통제)
  // ============================================================
  const PORT_SECURITY = [
    {
      name: '부산항보안공사',
      abbr: 'BPSC',
      port: '부산항',
      url: 'https://www.bpsc.co.kr',
      portKey: '부산항',
      role: '부산항만공사 자회사 — 부두 24시간 경비·ISPS·출입통제',
      address: '부산광역시 중구 충장대로 24, 부산항연안여객터미널 3층 (중앙동4가)',
      postcode: '48940',
      tel: '051-719-6021',
      fax: '0303-3444-9204',
      telBukhang: '051-719-6171',
      telGamcheon: '051-719-6173',
      telSinhang: '051-719-6175',
      note: '출입증: 북항 051-719-6171 / 감천 051-719-6173 / 신항 051-719-6175~6',
    },
    {
      name: '인천항보안공사',
      abbr: 'IPS',
      port: '인천항',
      url: 'https://port.co.kr',
      portKey: '인천항',
      role: '인천항만공사 자회사 — 인천항 + 신항 + 국제여객터미널 경비·ISPS',
      address: '인천광역시 중구 서해대로 365 (항동7가)',
      postcode: '22346',
      tel: '032-890-8300',
    },
  ];

  // ============================================================
  // 10. 무역항 (PORTS) — 13개 + 마커/카드용 데이터
  // ============================================================
  const REGION_COLORS = {
    수도권충청: '#14b8a6',
    호남: '#fbbf24',
    영남: '#f97316',
    동해안: '#ef4444',
    제주: '#a78bfa',
  };
  const PORTS = [
    {
      name: '부산항',
      nameEn: 'Port of Busan',
      locode: 'KRPUS',
      coords: [129.07, 35.10],
      region: '영남',
      color: REGION_COLORS.영남,
      authority: '부산지방해양수산청',
      authorityUrl: 'https://busan.mof.go.kr',
      pa: '부산항만공사 (BPA)',
      paUrl: 'https://www.busanpa.com',
      pilotage: '부산항도선사회',
      vts: 'CH 12, 14',
      facilities: '북항(재래/일반), 신항(컨테이너), 감천항, 다대포항',
      note: '세계 7위 컨테이너 항만, 세계 최상위권 환적 허브, 한국 최대 무역항',
      faircall: 'https://faircall.kr/regions/yeongnam/busan',
      guideUrl: 'https://faircast.kr/busan-port-transshipment-hub-30-year-strategy/',
    },
    {
      name: '인천항',
      nameEn: 'Port of Incheon',
      locode: 'KRINC',
      coords: [126.62, 37.45],
      region: '수도권·충청',
      color: REGION_COLORS.수도권충청,
      authority: '인천지방해양수산청',
      authorityUrl: 'https://incheon.mof.go.kr',
      pa: '인천항만공사 (IPA)',
      paUrl: 'https://www.icpa.or.kr',
      pilotage: '인천항도선사회',
      vts: 'CH 14',
      facilities: '내항(1~8부두), 남항, 북항, 신항(컨테이너), 연안여객',
      note: '수도권 관문, 컨테이너 + 자동차 + 카페리',
      faircall: 'https://faircall.kr/regions/capital/incheon',
      guideUrl: 'https://faircast.kr/incheon-port-tidal-lock-gate-explained/',
    },
    {
      name: '평택·당진항',
      nameEn: 'Port of Pyeongtaek-Dangjin',
      locode: 'KRPTK',
      coords: [126.83, 36.97],
      region: '수도권·충청',
      color: REGION_COLORS.수도권충청,
      authority: '평택지방해양수산청',
      authorityUrl: 'https://pyeongtaek.mof.go.kr',
      pa: '경기평택항만공사',
      paUrl: 'https://www.gppc.or.kr',
      pilotage: '평택항도선사회',
      vts: 'CH 14',
      facilities: '동부두, 서부두, 자동차전용, LNG돌핀, 한전돌핀, 현대제철',
      note: '자동차 수출 1위, LNG 도입 거점',
      faircall: 'https://faircall.kr/regions/capital/031',
      guideUrl: null,
    },
    {
      name: '대산항',
      nameEn: 'Port of Daesan',
      locode: 'KRDSN',
      coords: [126.36, 37.00],
      region: '수도권·충청',
      color: REGION_COLORS.수도권충청,
      authority: '대산지방해양수산청',
      authorityUrl: 'https://daesan.mof.go.kr',
      pa: '관할청 직접 운영',
      paUrl: null,
      pilotage: '대산항도선사회',
      vts: 'CH 11',
      facilities: '일반부두, 석유화학부두(현대오일뱅크/롯데케미칼/한화토탈/LG화학), SBM',
      note: '한국 3위 액체화물 항만, Suezmax~VLCC 접안',
      faircall: 'https://faircall.kr/regions/chungcheong/daesan',
      guideUrl: null,
    },
    {
      name: '군산항',
      nameEn: 'Port of Gunsan',
      locode: 'KRKUV',
      coords: [126.62, 35.98],
      region: '호남',
      color: REGION_COLORS.호남,
      authority: '군산지방해양수산청',
      authorityUrl: 'https://gunsan.mof.go.kr',
      pa: '관할청 직접 운영',
      paUrl: null,
      pilotage: '군산항도선사회',
      vts: 'CH 14',
      facilities: '일반부두, 잡화, 컨테이너, 자동차전용',
      note: '새만금 인근, 자동차 + 잡화',
      faircall: 'https://faircall.kr/regions/honam/gunsan',
      guideUrl: null,
    },
    {
      name: '목포항',
      nameEn: 'Port of Mokpo',
      locode: 'KRMOK',
      coords: [126.38, 34.78],
      region: '호남',
      color: REGION_COLORS.호남,
      authority: '목포지방해양수산청',
      authorityUrl: 'https://mokpo.mof.go.kr',
      pa: '관할청 직접 운영',
      paUrl: null,
      pilotage: '목포항도선사회',
      vts: 'CH 14',
      facilities: '내항, 남항, 신항(자동차/잡화), 연안여객',
      note: '서남해 거점, 도서 여객 + 자동차',
      faircall: 'https://faircall.kr/regions/honam/mokpo',
      guideUrl: null,
    },
    {
      name: '광양항',
      nameEn: 'Port of Gwangyang',
      locode: 'KRKAN',
      coords: [127.70, 34.90],
      region: '호남',
      color: REGION_COLORS.호남,
      authority: '여수지방해양수산청',
      authorityUrl: 'https://yeosu.mof.go.kr',
      pa: '여수광양항만공사 (YGPA)',
      paUrl: 'https://www.ygpa.or.kr',
      pilotage: '여수항도선사회',
      vts: 'CH 14 (광양만권)',
      facilities: '컨테이너, 일반, 원료(POSCO), 석유화학(GS칼텍스/여천NCC)',
      note: '광양만권 거점 항만, POSCO 원료 + 컨테이너 + 석유화학, VLCC 접안 가능',
      faircall: 'https://faircall.kr/regions/gwangyang-bay/gwangyang',
      guideUrl: 'https://faircast.kr/gwangyang-yeosu-port-division-korea-guide/',
    },
    {
      name: '여수항',
      nameEn: 'Port of Yeosu',
      locode: 'KRYOS',
      coords: [127.74, 34.74],
      region: '호남',
      color: REGION_COLORS.호남,
      authority: '여수지방해양수산청',
      authorityUrl: 'https://yeosu.mof.go.kr',
      pa: '여수광양항만공사 (YGPA)',
      paUrl: 'https://www.ygpa.or.kr',
      pilotage: '여수항도선사회',
      vts: 'CH 14 (광양만권)',
      facilities: '여수국가산업단지(LG화학/GS칼텍스 외), 컨테이너 + 일반',
      note: '여수 석유화학 단지 연결',
      faircall: 'https://faircall.kr/regions/gwangyang-bay/yeosu',
      guideUrl: 'https://faircast.kr/gwangyang-yeosu-port-division-korea-guide/',
    },
    {
      name: '마산항',
      nameEn: 'Port of Masan',
      locode: 'KRMAS',
      coords: [128.58, 35.20],
      region: '영남',
      color: REGION_COLORS.영남,
      authority: '마산지방해양수산청',
      authorityUrl: 'https://masan.mof.go.kr',
      pa: '관할청 직접 운영',
      paUrl: null,
      pilotage: '마산항도선사회',
      vts: 'CH 14',
      facilities: '일반부두, 컨테이너, 잡화',
      note: '창원·진해 산업 단지 연결',
      faircall: 'https://faircall.kr/regions/yeongnam/masan',
      guideUrl: null,
    },
    {
      name: '울산항',
      nameEn: 'Port of Ulsan',
      locode: 'KRUSN',
      coords: [129.42, 35.50],
      region: '영남',
      color: REGION_COLORS.영남,
      authority: '울산지방해양수산청',
      authorityUrl: 'https://ulsan.mof.go.kr',
      pa: '울산항만공사 (UPA)',
      paUrl: 'https://www.upa.or.kr',
      pilotage: '울산항도선사회',
      vts: 'CH 14',
      facilities: '본항, 미포항, 온산항, 신항, SBM (SK에너지/S-Oil)',
      note: '한국 최대 액체화물 항만, VLCC 접안',
      faircall: 'https://faircall.kr/regions/yeongnam/ulsan',
      guideUrl: 'https://faircast.kr/ulsan-port-petroleum-hub-future-clean-fuel-korea-guide/',
    },
    {
      name: '포항항',
      nameEn: 'Port of Pohang',
      locode: 'KRKPO',
      coords: [129.39, 36.04],
      region: '영남',
      color: REGION_COLORS.영남,
      authority: '포항지방해양수산청',
      authorityUrl: 'https://pohang.mof.go.kr',
      pa: '관할청 직접 운영',
      paUrl: null,
      pilotage: '포항항도선사회',
      vts: 'CH 12',
      facilities: '신항(POSCO 원료부두), 구항, 영일만항',
      note: 'POSCO 포항제철소 연결, 원료(철광석/석탄) 중심',
      faircall: 'https://faircall.kr/regions/yeongnam/pohang',
      guideUrl: null,
    },
    {
      name: '동해·묵호항',
      nameEn: 'Port of Donghae-Mukho',
      locode: 'KRDHE',
      coords: [129.13, 37.50],
      region: '동해안',
      color: REGION_COLORS.동해안,
      authority: '동해지방해양수산청',
      authorityUrl: 'https://donghae.mof.go.kr',
      pa: '관할청 직접 운영',
      paUrl: null,
      pilotage: '동해항도선사회',
      vts: 'CH 14',
      facilities: '일반부두, 시멘트, 잡화 (옥계/묵호 포함)',
      note: '동해안 산업 항만, 시멘트/석탄 중심',
      faircall: 'https://faircall.kr/regions/east-coast/donghae',
      guideUrl: null,
    },
    {
      name: '제주항',
      nameEn: 'Port of Jeju',
      locode: 'KRCJU',
      coords: [126.54, 33.52],
      region: '제주',
      color: REGION_COLORS.제주,
      authority: '제주지방해양수산청',
      authorityUrl: 'https://jeju.mof.go.kr',
      pa: '관할청 직접 운영',
      paUrl: null,
      pilotage: '제주항도선사회',
      vts: 'CH 12',
      facilities: '외항, 내항, 서귀포항, 한림항',
      note: '카페리 + 크루즈 + 연안 여객',
      faircall: 'https://faircall.kr/regions/jeju/jeju',
      guideUrl: null,
    },
  ];

  // ============================================================
  // 10. 해상교통관제센터 VTS (19개 — 4개 지방청 + 본청 해상교통관제과 통합 운영)
  // ============================================================
  const VTS_CENTERS = [
    // ===== 중부지방해양경찰청 (6) =====
    {
      name: '경인연안 VTS',
      abbr: 'Gyeongin Coastal VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=01&mi=2836',
      parent: '중부지방해양경찰청',
      channel: 'CH 71',
      address: '인천광역시 중구 영종해안북로1204번길 195',
      tel: '032-728-8456',
      telControl: '032-728-8656',
      fax: '032-728-8956',
      coverage: '덕적도 ~ 백령도 (서해 외해)',
    },
    {
      name: '경인항 VTS',
      abbr: 'Gyeongin VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=02&mi=2836',
      parent: '중부지방해양경찰청',
      channel: 'CH 9',
      address: '인천광역시 서구 정서진남로 95, 아라서해갑문 7층',
      tel: '032-728-8252',
      telControl: '032-728-8552',
      fax: '032-728-8452',
      coverage: '경인항 + 아라뱃길',
    },
    {
      name: '인천항 VTS',
      abbr: 'Incheon VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=14&mi=2836',
      portKey: '인천항',
      parent: '중부지방해양경찰청',
      channel: 'CH 14, 68',
      address: '인천광역시 중구 축항대로 9 (북성동1가)',
      tel: '032-728-8250',
      telControl: '032-728-8550',
      fax: '032-886-5703',
      coverage: '인천 교통안전특정해역 + 인천항',
    },
    {
      name: '평택항 VTS',
      abbr: 'Pyeongtaek VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=19&mi=2836',
      portKey: '평택·당진항',
      parent: '중부지방해양경찰청',
      channel: 'CH 10',
      address: '경기도 평택시 포승읍 평택항만길 73, 마린센터 13층',
      tel: '031-8046-2550',
      fax: '031-8046-2789',
      coverage: '평택·당진항 + 인근 (서해대교 통과)',
    },
    {
      name: '대산항 VTS',
      abbr: 'Daesan VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=04&mi=2836',
      portKey: '대산항',
      parent: '중부지방해양경찰청',
      channel: 'CH 12',
      address: '충청남도 서산시 대산읍 명지1로 213, 대산항해상교통관제센터 3층',
      tel: '041-950-2550',
      fax: '041-663-0349',
      coverage: '대산·태안·당진화력 + 보령 + 장안서',
      note: '대산VTS(CH12) + 장안VTS(CH67) + 보령VTS(CH69) 통합 운영',
    },
    {
      name: '태안연안 VTS',
      abbr: 'Taean Coastal VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=17&mi=2836',
      parent: '중부지방해양경찰청',
      coverage: '태안 연안 해역 (2018.7 신설)',
    },
    // ===== 서해지방해양경찰청 (5) =====
    {
      name: '군산광역 VTS',
      abbr: 'Gunsan VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=03&mi=2836',
      portKey: '군산항',
      parent: '서해지방해양경찰청',
      channel: 'CH 12, 71',
      address: '전라북도 군산시 서해로 503',
      tel: '061-288-2130',
      fax: '061-288-2933',
      coverage: '군산·장항항 + 어청도~안마도',
      note: '군산 + 군산연안 통합 (2023.9)',
    },
    {
      name: '목포광역 VTS',
      abbr: 'Mokpo VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=07&mi=2836',
      portKey: '목포항',
      parent: '서해지방해양경찰청',
      coverage: '목포·진도·신안 연안',
      note: '목포·진도연안 + 신안연안 통합 (2023.9)',
    },
    {
      name: '여수항 VTS',
      abbr: 'Yeosu VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=11&mi=2836',
      portKey: '광양항',
      parent: '서해지방해양경찰청',
      channel: 'CH 12 (여수), CH 67 (광양)',
      address: '전라남도 여수시 자산공원길 90, 자산공원 내',
      tel: '061-288-2570',
      fax: '061-288-2970',
      coverage: '여수·광양항 + 항계 밖 정박지 (이순신대교·묘도대교)',
    },
    {
      name: '여수연안 VTS',
      abbr: 'Yeosu Coastal VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=10&mi=2836',
      parent: '서해지방해양경찰청',
      channel: 'CH 71',
      address: '전라남도 여수시 화정면 백야등대길 48',
      tel: '061-288-2569',
      fax: '061-288-2969',
      coverage: '구도 ~ 소리도 (여수 외해)',
    },
    {
      name: '완도항 VTS',
      abbr: 'Wando VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=12&mi=2836',
      parent: '서해지방해양경찰청',
      channel: 'CH 10',
      address: '전라남도 완도군 완도읍 장보고대로 365',
      tel: '061-288-2251',
      fax: '061-288-2951',
      coverage: '완도·청산도·신지도 + 인근',
    },
    // ===== 남해지방해양경찰청 (5) =====
    {
      name: '울산항 VTS',
      abbr: 'Ulsan VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=13&mi=2836',
      portKey: '울산항',
      parent: '남해지방해양경찰청',
      channel: 'CH 14',
      address: '울산광역시 남구 장생포고래로276번길 25',
      tel: '052-230-2550',
      fax: '052-230-2850',
      coverage: '울산 본항·온산항·신항·남항',
    },
    {
      name: '부산신항 VTS',
      abbr: 'Busan New Port VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=08&mi=2836',
      portKey: '부산항',
      parent: '남해지방해양경찰청',
      channel: 'CH 10',
      address: '경상남도 창원시 진해구 연도로 58',
      tel: '051-663-2550',
      fax: '055-545-0406',
      coverage: '부산신항 + 가덕수도',
    },
    {
      name: '부산항 VTS',
      abbr: 'Busan VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=09&mi=2836',
      portKey: '부산항',
      parent: '남해지방해양경찰청',
      channel: 'CH 12, 9',
      address: '부산광역시 영도구 해양로 301번길 13',
      tel: '051-664-2750',
      telOffice: '051-664-2250',
      fax: '051-663-2950',
      coverage: '북항 + 감천항 + 남외항 정박지',
    },
    {
      name: '마산항 VTS',
      abbr: 'Masan VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=06&mi=2836',
      portKey: '마산항',
      parent: '남해지방해양경찰청',
      channel: 'CH 14 (마산), CH 67 (옥포)',
      address: '경상남도 창원시 마산합포구 제2부두로 30, 경남지방합동청사 항만동 4층',
      tel: '055-981-2550',
      fax: '055-981-2850',
      coverage: '마산·진해·고현·옥포·안정항',
    },
    {
      name: '통영연안 VTS',
      abbr: 'Tongyeong Coastal VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=18&mi=2836',
      parent: '남해지방해양경찰청',
      channel: 'CH 69',
      address: '경상남도 통영시 서송정길 56',
      tel: '055-647-2550',
      fax: '055-647-2950',
      coverage: '욕지도·매물도 + 삼천포항',
    },
    // ===== 동해지방해양경찰청 (2) =====
    {
      name: '동해광역 VTS',
      abbr: 'Donghae VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=05&mi=2836',
      portKey: '동해·묵호항',
      parent: '동해지방해양경찰청',
      channel: 'CH 12 (동해/삼척/묵호/옥계/안인), CH 14 (호산/속초)',
      address: '강원특별자치도 동해시 임항로 129 (발한동)',
      tel: '033-680-2550',
      fax: '033-680-2850',
      coverage: '동해·묵호·삼척·옥계·안인 + 호산·속초 (단순 입출항)',
    },
    {
      name: '포항광역 VTS',
      abbr: 'Pohang VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=20&mi=2836',
      portKey: '포항항',
      parent: '동해지방해양경찰청',
      channel: 'CH 12',
      address: '경상북도 포항시 북구 흥해읍 용한리 909',
      tel: '054-750-2550',
      fax: '054-750-2850',
      coverage: '포항 신항·영일만항·구항',
    },
    // ===== 제주지방해양경찰청 (1) =====
    {
      name: '제주광역 VTS',
      abbr: 'Jeju VTS',
      url: 'https://www.kcg.go.kr/kcg/si/sub/info.do?page=2836&num=15&mi=2836',
      portKey: '제주항',
      parent: '제주지방해양경찰청',
      channel: 'CH 9 (북부 통과), CH 12 (북부 연안), CH 14 (남부 서귀포)',
      address: '제주특별자치도 제주시 임항로 195 (건입동)',
      tel: '064-801-2550',
      telSeogwipo: '064-801-2860',
      fax: '064-801-2850',
      coverage: '제주 북부·남부 전 연안 + 추자도',
      note: '제주 + 서귀포 통합 (2024.9)',
    },
  ];

  // ============================================================
  // 전역 노출
  // ============================================================
  window.PORT_ATLAS_DATA = {
    PORTS,
    MOF,
    OFFICES,
    PORT_AUTHORITIES,
    PILOTS,
    MOF_AGENCIES,
    CUSTOMS_HQ,
    CUSTOMS_PORTS,
    KCG_AGENCIES,
    QUARANTINE_AGENCIES,
    PORT_SECURITY,
    VTS_CENTERS,
  };
})();
